update-work-readme:
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name 'Kev'
    - git clone https://kkloss:${KEV_WORK_TOKEN}@gitlab.com/kkloss/kkloss.git
    - ./cmd/generate-work-readme.sh > kkloss/README.md
    - cd kkloss
    - git add README.md
    - git commit -m 'Update README.md from KevSlashNull/KevSlashNull'
    - git push -o ci.skip
  only: [main]
