update-work-readme:
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name 'Kev'
    - git clone https://kkloss:${KEV_WORK_TOKEN}@gitlab.com/kkloss/kkloss.git
    - ./cmd/generate-work-readme.sh > kkloss/README.md
    - cd kkloss
    - git add README.md
    - git commit -m 'Update README.md from KevSlashNull/KevSlashNull' || (echo 'Couldn’t commit'; exit 69)
    - git push -o ci.skip
  allow_failure:
    exit_codes: 69
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - README.md
        - cmd/*.sh
        - .gitlab-ci.yml

work-readme-test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - ./cmd/generate-work-readme.sh
    